config/routes.rb
Rails.application.routes.draw do

  resources :meal_recipes do 
  resources :reviews
  end 

controller :sessions do
	get 'login' => :new 
	post 'login' => :create 
	get 'logout' => :destroy
	delete 'logout' => :destroy
end 

  resources :special_recipes

  resources :diets

  resources :meal_recipes

  resources :users

 root 'pages#home'

end

app/models/meal_recipe.rb
class MealRecipe < ActiveRecord::Base
	belongs_to :user
	
	has_many :reviews,:dependent=>  :destroy
	has_many :specialRecipes,dependent:  :destroy
	validates :recipeName, presence: true
	validates :recipeName, uniqueness: true
	validates :difficultyLevel, presence: true
	 def average_stars
		reviews.average(:stars)
	end
end

app/controllers/meal_recipes_controller.rb
class MealRecipesController < ApplicationController
  before_action :set_meal_recipe, only: [:show, :edit, :update, :destroy]
 before_action :authorise, :only => [:new, :create, :edit, :update, :delete]
  # GET /meal_recipes
  # GET /meal_recipes.json
  def index
    @meal_recipes = MealRecipe.all
  end

  # GET /meal_recipes/1
  # GET /meal_recipes/1.json
  def show
  end

  # GET /meal_recipes/new
  def new
    @meal_recipe = MealRecipe.new
  end

  # GET /meal_recipes/1/edit
  def edit
  end

  # POST /meal_recipes
  # POST /meal_recipes.json
  def create
    @meal_recipe = MealRecipe.new(meal_recipe_params)

    respond_to do |format|
      if @meal_recipe.save
        format.html { redirect_to @meal_recipe, notice: 'Meal recipe was successfully created.' }
        format.json { render :show, status: :created, location: @meal_recipe }
      else
        format.html { render :new }
        format.json { render json: @meal_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meal_recipes/1
  # PATCH/PUT /meal_recipes/1.json
  def update
    respond_to do |format|
      if @meal_recipe.update(meal_recipe_params)
        format.html { redirect_to @meal_recipe, notice: 'Meal recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal_recipe }
      else
        format.html { render :edit }
        format.json { render json: @meal_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meal_recipes/1
  # DELETE /meal_recipes/1.json
  def destroy
    @meal_recipe.destroy
    respond_to do |format|
      format.html { redirect_to meal_recipes_url, notice: 'Meal recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal_recipe
      @meal_recipe = MealRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meal_recipe_params
      params.require(:meal_recipe).permit(:mealType, :image, :instructions, :user_id, :dateOfUpload, :recipeName, :servingQuantity, :difficultyLevel)
    end
end

app/helpers/meal_recipes_helper.rb
module MealRecipesHelper
end

app/views/meal_recipes/_form.html.erb
<%= form_for(@meal_recipe) do |f| %>
  <% if @meal_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal_recipe.errors.count, "error") %> prohibited this meal_recipe from being saved:</h2>

      <ul>
      <% @meal_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mealType %><br>
    <%= f.text_field :mealType %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :instructions %><br>
    <%= f.text_area :instructions %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
<%=f.collection_select :user_id, User.all, :id, :nameOfUser%>
  </div>
  <div class="field">
    <%= f.label :dateOfUpload %><br>
    <%= f.date_select :dateOfUpload %>
  </div>
  <div class="field">
    <%= f.label :recipeName %><br>
    <%= f.text_field :recipeName %>
  </div>
  <div class="field">
    <%= f.label :servingQuantity %><br>
    <%= f.number_field :servingQuantity %>
  </div>
  <div class="field">
    <%= f.label :difficultyLevel %><br>
    <%= f.text_field :difficultyLevel %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meal_recipes/edit.html.erb
<h1>Editing meal_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal_recipe %> |
<%= link_to 'Back', meal_recipes_path %>

app/views/meal_recipes/index.html.erb
<div class="container">
<head>
  <title>List of all Recipes</title>
</head>

<table class="table table-bordered">
  <thead>
    <tr class="info">
      <th>Mealtype</th>
      <th>Image</th>
      
      <th>Uploaded by</th>
      <th>Date of upload</th>
      <th>Recipe Name</th>
      <th>Serving Quantity</th>
      <th>Difficulty </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meal_recipes.each do |meal_recipe| %>
      <tr>
        <td><%= meal_recipe.mealType %></td>
       <td><%= image_tag(meal_recipe.image,:size=>"80x50")%></td>
        
        <td><%= meal_recipe.user.nameOfUser %></td>
        <td><%= meal_recipe.dateOfUpload %></td>
        <td><%= meal_recipe.recipeName %></td>
        <td><%= meal_recipe.servingQuantity %></td>
        <td><%= meal_recipe.difficultyLevel %></td>
        <td><%= link_to 'View', meal_recipe %></td>
        <td><%= link_to 'Edit', edit_meal_recipe_path(meal_recipe) %></td>
        <td><%= link_to 'Destroy', meal_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><%= link_to 'New Meal recipe', new_meal_recipe_path %></strong>

app/views/meal_recipes/new.html.erb
<h1>New meal_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', meal_recipes_path %>

app/views/meal_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type</strong>
  <%= @meal_recipe.mealType %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@meal_recipe.image,:size=>"80x50")%>
</p>

<p>
  <strong>Instructions:</strong>
  <%= @meal_recipe.instructions %>
</p>

<p>
  <strong>User:</strong>
  <%= @meal_recipe.user.nameOfUser %>
</p>

<p>
  <strong>Dateofupload:</strong>
  <%= @meal_recipe.dateOfUpload %>
</p>

<p>
  <strong>Recipename:</strong>
  <%= @meal_recipe.recipeName %>
</p>

<p>
  <strong>Servingquantity:</strong>
  <%= @meal_recipe.servingQuantity %>
</p>

<p>
  <strong>Difficultylevel:</strong>
  <%= @meal_recipe.difficultyLevel %>
</p>

<h2>Star Rating and Review:</h2>
	<%=form_for([@meal_recipe, Review.new]) do |f| %>
	
<h3><%= f.label :stars %> 
	<%stars = [1,2,3,4,5] %> 
	<%stars.each do |star| %>
		<%= f.radio_button :stars, star %> <% star %> 
	<% end %> 
</h3><br> 
<%= f.text_area :content, :rows => 4, :cols => 40 %> 
<div class="actions">
	<%= f.submit "Please leave a Review"%> 
</div> 
<% end %> 

<% if @meal_recipe.reviews.empty? %> 
	<h3>You are the first to publish a review</h3> 
<% else %> 
	<h2>What others felt about this Recipe:</h2> 
	<% @meal_recipe.reviews.reverse.each do |review| %> 
		<p><%= review.content %>
		Posted <%= time_ago_in_words(review.created_at) %> ago by
		<%=review.user.nameOfUser %></p>
	<% end %> 
	<h3>Average Rating</h3>
	<p>
		<%= number_with_precision( @meal_recipe.average_stars, precision: 0) %> 
	</p>
<% end %>

<%= link_to 'Edit', edit_meal_recipe_path(@meal_recipe) %> |
<%= link_to 'Back', meal_recipes_path %>