config/routes.rb
Rails.application.routes.draw do

  resources :meal_recipes do 
  resources :reviews
  end 

controller :sessions do
	get 'login' => :new 
	post 'login' => :create 
	get 'logout' => :destroy
	delete 'logout' => :destroy
end 

  resources :special_recipes

  resources :diets

  resources :meal_recipes

  resources :users

 root 'pages#home'

end

app/models/diet.rb
class Diet < ActiveRecord::Base
		has_many :specialRecipies, dependent: :destroy
		validates :dietaryNeed, presence: true
	validates :dietaryNeed, uniqueness: true
end

app/controllers/diets_controller.rb
class DietsController < ApplicationController
  before_action :set_diet, only: [:show, :edit, :update, :destroy]

  # GET /diets
  # GET /diets.json
  def index
    @diets = Diet.all
  end

  # GET /diets/1
  # GET /diets/1.json
  def show
  end

  # GET /diets/new
  def new
    @diet = Diet.new
  end

  # GET /diets/1/edit
  def edit
  end

  # POST /diets
  # POST /diets.json
  def create
    @diet = Diet.new(diet_params)

    respond_to do |format|
      if @diet.save
        format.html { redirect_to @diet, notice: 'Diet was successfully created.' }
        format.json { render :show, status: :created, location: @diet }
      else
        format.html { render :new }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diets/1
  # PATCH/PUT /diets/1.json
  def update
    respond_to do |format|
      if @diet.update(diet_params)
        format.html { redirect_to @diet, notice: 'Diet was successfully updated.' }
        format.json { render :show, status: :ok, location: @diet }
      else
        format.html { render :edit }
        format.json { render json: @diet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diets/1
  # DELETE /diets/1.json
  def destroy
    @diet.destroy
    respond_to do |format|
      format.html { redirect_to diets_url, notice: 'Diet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_diet
      @diet = Diet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def diet_params
      params.require(:diet).permit(:dietaryNeed)
    end
end

app/helpers/diets_helper.rb
module DietsHelper
end

app/views/diets/_form.html.erb
<%= form_for(@diet) do |f| %>
  <% if @diet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@diet.errors.count, "error") %> prohibited this diet from being saved:</h2>

      <ul>
      <% @diet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dietaryNeed %><br>
    <%= f.text_field :dietaryNeed %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diets/edit.html.erb
<h1>Editing diet</h1>

<%= render 'form' %>

<%= link_to 'Show', @diet %> |
<%= link_to 'Back', diets_path %>

app/views/diets/index.html.erb
<h1>Different Types of diets</h1>

<table>
  <thead>
    <tr>
      <th>Dietaryneed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diets.each do |diet| %>
      <tr>
        <td><%= diet.dietaryNeed %></td>
        <td><%= link_to 'Show', diet %></td>
        <td><%= link_to 'Edit', edit_diet_path(diet) %></td>
        <td><%= link_to 'Destroy', diet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Diet', new_diet_path %>

app/views/diets/new.html.erb
<h1>New diet</h1>

<%= render 'form' %>

<%= link_to 'Back', diets_path %>

app/views/diets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dietaryneed:</strong>
  <%= @diet.dietaryNeed %>
</p>

<%= link_to 'Edit', edit_diet_path(@diet) %> |
<%= link_to 'Back', diets_path %>