config/routes.rb
Rails.application.routes.draw do

  resources :meal_recipes do 
  resources :reviews
  end 

controller :sessions do
	get 'login' => :new 
	post 'login' => :create 
	get 'logout' => :destroy
	delete 'logout' => :destroy
end 

  resources :special_recipes

  resources :diets

  resources :meal_recipes

  resources :users

 root 'pages#home'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
 <head>
  <title>Recipe Explorer</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

	<nav class="navbar navbar-inverse">

  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" root_path>Recipe Explorer</a>
	  
	  <%= image_tag("banner-photo.jpg",:size => "100x60")%>
    </div>
    <ul class="nav navbar-nav">
      
	  <li><%=link_to "Home", root_path %></li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"> All Recipes <span class="caret"></span></a>
        <ul class="dropdown-menu">
		 <li><%=link_to"Recipes",meal_recipes_path%></li>
          
        </ul>
      </li>
      <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#"> Our Users<span class="caret"></span></a>
        <ul class="dropdown-menu">
		 <li><%=link_to"Our Users",users_path%></li>
		 </li>
		 <ul class="nav navbar-nav navbar-center">
			<% if !signed_in?%>
			<li><%=link_to "Sign In",login_path%></li>
			<%else%>
				<li>Signed in as <%=@current_user.nameOfUser%></li>
				<li><%= link_to "Sign Out", logout_path%></li>
			<%end%>
		</ul>
		
      
			</ul>
	
  
			</div>
		</div>
	</nav>
 


  
<%= yield %>

</body>
</html>