config/routes.rb
Rails.application.routes.draw do

  resources :meal_recipes do 
  resources :reviews
  end 

controller :sessions do
	get 'login' => :new 
	post 'login' => :create 
	get 'logout' => :destroy
	delete 'logout' => :destroy
end 

  resources :special_recipes

  resources :diets

  resources :meal_recipes

  resources :users

 root 'pages#home'

end

app/models/special_recipe.rb
class SpecialRecipe < ActiveRecord::Base
		belongs_to :diet
		belongs_to :mealRecipe
end

app/controllers/special_recipes_controller.rb
class SpecialRecipesController < ApplicationController
  before_action :set_special_recipe, only: [:show, :edit, :update, :destroy]

  # GET /special_recipes
  # GET /special_recipes.json
  def index
    @special_recipes = SpecialRecipe.all
  end

  # GET /special_recipes/1
  # GET /special_recipes/1.json
  def show
  end

  # GET /special_recipes/new
  def new
    @special_recipe = SpecialRecipe.new
  end

  # GET /special_recipes/1/edit
  def edit
  end

  # POST /special_recipes
  # POST /special_recipes.json
  def create
    @special_recipe = SpecialRecipe.new(special_recipe_params)

    respond_to do |format|
      if @special_recipe.save
        format.html { redirect_to @special_recipe, notice: 'Special recipe was successfully created.' }
        format.json { render :show, status: :created, location: @special_recipe }
      else
        format.html { render :new }
        format.json { render json: @special_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /special_recipes/1
  # PATCH/PUT /special_recipes/1.json
  def update
    respond_to do |format|
      if @special_recipe.update(special_recipe_params)
        format.html { redirect_to @special_recipe, notice: 'Special recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @special_recipe }
      else
        format.html { render :edit }
        format.json { render json: @special_recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /special_recipes/1
  # DELETE /special_recipes/1.json
  def destroy
    @special_recipe.destroy
    respond_to do |format|
      format.html { redirect_to special_recipes_url, notice: 'Special recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_special_recipe
      @special_recipe = SpecialRecipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def special_recipe_params
      params.require(:special_recipe).permit(:Diet_id, :mealRecipe_id)
    end
end

app/helpers/special_recipes_helper.rb
module SpecialRecipesHelper
end

app/views/special_recipes/_form.html.erb
<%= form_for(@special_recipe) do |f| %>
  <% if @special_recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@special_recipe.errors.count, "error") %> prohibited this special_recipe from being saved:</h2>

      <ul>
      <% @special_recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Diet_id %><br>
    <%= f.number_field :Diet_id %>
  </div>
  <div class="field">
    <%= f.label :meal_Recipe.id %><br>
    <%= f.number_field :meal_recipe.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/special_recipes/edit.html.erb
<h1>Editing special_recipe</h1>

<%= render 'form' %>

<%= link_to 'Show', @special_recipe %> |
<%= link_to 'Back', special_recipes_path %>

app/views/special_recipes/index.html.erb
<h1>Listing special_recipes</h1>

<table>
  <thead>
    <tr>
      <th>Diet</th>
      <th>Mealrecipe</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @special_recipes.each do |special_recipe| %>
      <tr>
        <td><%= special_recipe.Diet_id %></td>
        <td><%= special_recipe.mealRecipe_id %></td>
        <td><%= link_to 'Show', special_recipe %></td>
        <td><%= link_to 'Edit', edit_special_recipe_path(special_recipe) %></td>
        <td><%= link_to 'Destroy', special_recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Special recipe', new_special_recipe_path %>

app/views/special_recipes/new.html.erb
<h1>New special_recipe</h1>

<%= render 'form' %>

<%= link_to 'Back', special_recipes_path %>

app/views/special_recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Diet:</strong>
  <%= @special_recipe.Diet_id %>
</p>

<p>
  <strong>Mealrecipe:</strong>
  <%= @special_recipe.mealRecipe_id %>
</p>

<%= link_to 'Edit', edit_special_recipe_path(@special_recipe) %> |
<%= link_to 'Back', special_recipes_path %>